ALM Upgrade/Controllers/Customer_ProjectController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ALM_Upgrade.Models;
using System.IO;
using System.Text.RegularExpressions;
using System.ComponentModel.DataAnnotations;
using System.Data.SqlClient;
using System.Data.Entity.Infrastructure;

namespace ALM_Upgrade.Controllers
{
    public class Customer_ProjectController : Controller
    {
        private ALMEntities db = new ALMEntities();

        // GET: Customer_Project
        public ActionResult Index()
        {
            if (Utilities.IsUserLogged())
            {
                return View(db.Customer_Project.ToList());
            }
            else
            {
                return RedirectToAction("Login", "Home");
            }

        }

        // GET: Customer_Project/Details/5
        public ActionResult Details(int? id)
        {
            if (Utilities.IsUserLogged())
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Customer_Project customer_Project = db.Customer_Project.Find(id);
                if (customer_Project == null)
                {
                    return HttpNotFound();
                }
                return View(customer_Project);
            }
            else
            {
                return RedirectToAction("Login", "Home");
            }
        }

        // GET: Customer_Project/Create
        public ActionResult Create()
        {
            if (Utilities.IsUserLogged())
            {
                return View();
            }
            else
            {
                return RedirectToAction("Login", "Home");
            }

        }

        // POST: Customer_Project/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,customer_name,customer_url,deactivation,undo_checkouts,copy_file,copy_db,change_file,restore_project,verify_project,upgrade_project,verification,deactivation,release,initialNotification,finalNotification,service_id,upgrade_type,upgrade_version,dry_run")] Customer_Project customer_Project)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    if (customer_Project.customer_name.Contains("batch"))
                        customer_Project.customer_name.Replace("batch", "Batch");
  
                    customer_Project.customerId = Guid.NewGuid();
                    db.Customer_Project.Add(customer_Project);
                    db.SaveChanges();
                    return RedirectToAction("Edit", new { id = customer_Project.id });
                }
                catch (Exception ex)
                {
                    if (ex.GetBaseException().GetType() == typeof(SqlException))
                    {
                        //Violation of primary key/Unique constraint can be handled here. Also you may //check if Exception Message contains the constraint Name 
                        String m = ex.InnerException.InnerException.Message;
                        if (m.Contains("Violation of UNIQUE KEY constraint"))
                        {
                            Session["message"] = "The customer name is already in use";
                            return View(customer_Project);
                        }
                    }
                }
                
            }

            return View(customer_Project);
        }

        // GET: Customer_Project/Edit/5
        public ActionResult Edit(int? id)
        {
            if (Utilities.IsUserLogged())
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Customer_Project customer_Project = db.Customer_Project.Find(id);
                if (customer_Project == null)
                {
                    return HttpNotFound();
                }

                if(customer_Project.deactivation == true && customer_Project.copy_file == true && customer_Project.copy_db == true && 
                    customer_Project.change_file == true && customer_Project.restore_project == true && customer_Project.upgrade_project ==true &&
                    customer_Project.undo_checkouts == true && customer_Project.verify_project ==  true && customer_Project.verification == true &&
                    customer_Project.release == true)
                {
                    ViewBag.allchecks = true;
                }
                else {
                    ViewBag.allchecks = false; 
                }
                return View(customer_Project);
            }
            else
            {
                return RedirectToAction("Login", "Home");
            }
        }

        // POST: Customer_Project/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,customer_name,customer_url,deactivation,undo_checkouts,copy_file,copy_db,change_file,restore_project,verify_project,upgrade_project,verification,release,customerId,initialNotification,finalNotification,service_id,upgrade_type,upgrade_version,dry_run")] Customer_Project customer_Project)
        {
            if (ModelState.IsValid)
            {
                db.Entry(customer_Project).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Edit", new { id = customer_Project.id });//return to same view
            }
                return View(customer_Project);
        }

        // GET: Customer_Project/Delete/5
        public ActionResult Delete(int? id)
        {
            if (Utilities.IsUserLogged())
            {
                Customer_Project customer_Project = db.Customer_Project.Find(id);
                db.Customer_Project.Remove(customer_Project);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            else
            {
                return RedirectToAction("Login", "Home");
            }
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public PartialViewResult Emails(int id)
        {
            List<Project_Email> emails = db.Project_Email.Where(x => x.project_id == id).ToList();
            return PartialView("Emails", emails);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public PartialViewResult ProjectList(int id)
        {
            List<ProjectList> projects = db.ProjectList.Where(x => x.customer_project_id == id).ToList();
            return PartialView("ProjectList", projects);
        }

        /// <summary>
        /// Gets tthe list of the finished projects for a customer
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public PartialViewResult FinishedProjectList(int id)
        {
            List<ProjectList> projects = db.ProjectList.Where(x => x.customer_project_id == id).Where(x => x.finished == true).OrderBy(x => x.domain_name).ToList();
            return PartialView("FinishedProjectList", projects);
        }

        /// <summary>
        /// saves in the db the status for a specific project
        /// </summary>
        /// <param name="id"></param>
        /// <param name="state"></param>
        /// <returns></returns>
        public JsonResult ProjectFinished(int id, int state)
        {
            try
            {
                ProjectList p = db.ProjectList.Find(id);
                p.finished = (state == 1) ? true : false;
                db.SaveChanges();
                return Json("Correct", JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            { return Json("Error", JsonRequestBehavior.AllowGet); }
        }


        [HttpPost]
        public ActionResult AddProjectList(int id)
        {
            //delete any entries for this project id
            db.ProjectList.RemoveRange(db.ProjectList.Where(x => x.customer_project_id == id));
            db.SaveChanges();
            try
            {
                HttpPostedFileBase projectList = Request.Files[0];
                // Use the InputStream to get the actual stream sent.
                StreamReader csvreader = new StreamReader(projectList.InputStream);
                char[] delimiters = new char[] { ';', ',' };
                while (!csvreader.EndOfStream)
                {
                    var line = csvreader.ReadLine();
                    var values = line.Split(delimiters, StringSplitOptions.RemoveEmptyEntries);
                    ProjectList pl = new ProjectList();
                    pl.domain_name = values[0];
                    pl.project_name = values[1];
                    pl.finished = false;
                    pl.customer_project_id = id;
                    db.ProjectList.Add(pl);
                }
                db.SaveChanges();
                return Json("Project list uploaded successfully!");
            }
            catch (Exception ex)
            {
                //delete any entries for this project id
                db.ProjectList.RemoveRange(db.ProjectList.Where(x => x.customer_project_id == id));
                db.SaveChanges();
                return Json("Error uploading file");
            }
        }

ALM Upgrade/Controllers/HomeController.cs
using ALM_Upgrade.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace ALM_Upgrade.Controllers
{
    public class HomeController : Controller
    {
        private ALMEntities db = new ALMEntities();

        public ActionResult Index()
        {
            if(Utilities.IsUserLogged())
            {
                return View();
            }
            else
            {
                return RedirectToAction("Login");
            }
            
        }

        public ActionResult NotFound()
        {
            return View();
        }

        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(string UserName, string Password)
        {
            String r = Utilities.Encrypt(Password);
            if (ModelState.IsValid)
            {
                try
                {
                    
                    int result = (int)(db.AutenticateUser(UserName, Utilities.Encrypt(Password)).First());
                    Session["user_logged"] = true;
                    Session["user_id"] = result;
                    Users us = db.Users.Find(result);
                    Session["username"] = us.UserName;
                    Session["user_email"] = us.Email;
                    Session["user_pass"] = Password;
                }
                catch (Exception ex)
                {
                    //if no succedded, to the login page
                    Session["message"] = "Please check your credentials and try again";
                    return View("Login");

                }
            }
            //if succedded, to the homepage
            return RedirectToAction("Index");
        }

        public ActionResult LogOut()
        {
            Session["user_logged"] = false;
            return RedirectToAction("Login", "Home");
        }

        /// <summary>
        /// Generic method for guest users
        /// redirects to a marjoincident dashboard with a guest user
        /// </summary>
        /// <returns></returns>
        public ActionResult Dashboard(int? incidentNumber, String user)
        {
            //http://localhost:24062/Home/Dashboard/?incidentNumber=135102&user=Guest
            //put code here
            Session["username"] = "Guest";
            return RedirectToAction("Dashboard", "MajorIncidents",new { id = incidentNumber });
        }

        public ActionResult ForgotPassword()
        {
            return View();
        }

        [HttpPost]
        public ActionResult ForgotPassword(string UserName)
        {
            try
            {
                List<Users> users = db.Users.Where(x => x.Email == UserName).ToList();
                if (users.Count == 1)
                {//the email is rgistered in the system
                    String newPass = Guid.NewGuid().ToString();
                    EmailHandler email = new EmailHandler();
                    Boolean result = email.SendRecoveryPassword(UserName, newPass);
                    if (result == true)
                    {
                        users[0].Emailpass = Utilities.Encrypt(newPass);
                        db.SaveChanges();
                    }
                }
                else
                {
                    Session["message"] = "Your email is not registered into the system.";
                    return View();
                }
                Session["message"] = "A recovery email has been sent. Please check your inbox.";
                return RedirectToAction("Login");
            }
            catch (Exception ex)
            {
                return View();
            }

        }
    }
}

ALM Upgrade/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

ALM Upgrade/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

ALM Upgrade/Views/Home/ForgotPassword.cshtml
@{
    ViewBag.Title = "Forgot Password";
    Layout = "~/Views/Shared/Login.cshtml";
}

<section class="login_content">

    @using (Html.BeginForm())
    {
        <h1>Password Recovery</h1>
        <h2>Please enter you email address and we'll send you the recovery password</h2>
        <div>
            <input type="email" class="form-control" name="UserName" placeholder="Email..." required="" />
        </div>
        <div class="row text-center">
            <input type="submit" value="Submit" class="btn btn-success" style="float:none;margin-left:0;" />
            
            <!--<a class="reset_pass" href="#">Lost your password?</a>-->
        </div>
        <div class="clearfix"></div>
        <div class="separator">
            <div class="clearfix"></div>
            <br />
            <div>
                <h1><i class="fa fa-tasks"></i> ALM Upgrade</h1>
            </div>
        </div>
    }

</section>

ALM Upgrade/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="row">
    <div class="animated flipInY col-lg-3 col-md-3 col-sm-6 col-xs-12">
        <div class="tile-stats">
            <div class="icon"><i class="fa fa-bookmark"></i></div>
            <div class="count">ALM Upgrade</div>
            <h3>@Html.ActionLink("List", "Index", "Customer_Project", null, new { })  | @Html.ActionLink("Create", "Create", "Customer_Project", null, new { }) </h3>
        </div>
    </div>

    <div class="animated flipInY col-lg-3 col-md-3 col-sm-6 col-xs-12">
        <div class="tile-stats">
            <div class="icon"><i class="fa fa-user"></i></div>
            <div class="count">User Management</div>
            <h3>@Html.ActionLink("List", "Index", "Users", null, new { })  | @Html.ActionLink("Create", "Create", "Users", null, new { }) </h3>
        </div>
    </div>
</div>

ALM Upgrade/Views/Home/Login.cshtml
@{
    Layout = "~/Views/Shared/Login.cshtml";
}

<section class="login_content">

    @using (Html.BeginForm())
    {
        <h1>ALM Login</h1>
        <div>
            <input type="email" class="form-control" name="UserName" placeholder="Email..." required="" />
        </div>
        <div>
            <input type="password" class="form-control" name="Password" placeholder="Password..." required="" />
        </div>
        <div class="row text-center">
            <input type="submit" value="Login" class="btn btn-success" style="float:none;margin-left:0;" />
            @Html.ActionLink("Forgot your password?", "ForgotPassword")
        </div>
        <div class="clearfix"></div>
        <div class="separator" style="background: #fff;    padding: 20px;">
            <div class="clearfix"></div>
            <br />
            <div>
                <h1><i class="fa fa-tasks"></i> ALM Upgrade</h1>
            </div>
        </div>
    }

</section>

ALM Upgrade/Views/Home/NotFound.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Gentelella Alela! | </title>
    <!-- Bootstrap -->
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <!-- Font Awesome -->
    <link href="~/Content/font-awesome.css" rel="stylesheet" />
    <!-- Custom Theme Style -->
    <link href="~/Content/custom.css" rel="stylesheet" />
</head>
<body class="nav-md" style="background:linear-gradient(to top,#1ab1c7,#2cc4c4);color:#fff;">
    <div class="container body">
        <div class="main_container">
            <!-- page content -->
            <div class="col-md-12">
                <div class="col-middle">
                    <div class="text-center text-center mid_center">
                        <h1 class="error-number">404</h1>
                        <h2>Sorry but we couldn't find this page</h2>
                        <p>
                           This page you are looking for does not exist <br/><a href="~/" style="color:#fff;">Back to Home Page</a>
                        </p>
                    </div>
                </div>
            </div>
            <!-- /page content -->
        </div>
    </div>
    <!-- jQuery -->
    <script src="~/Scripts/jquery.js"></script>
    <!-- Bootstrap -->
    <script src="~/Scripts/bootstrap.min.js"></script>
    <!-- Custom Theme Scripts -->
    <script src="~/Scripts/custom.min.js"></script>
</body>
</html>